version: '3.4'

services:
  frontend:
    image: morishima/frontend
    build:
      context: .
      dockerfile: FrontEnd/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "80:80"
    volumes:
      - ~/.aspnet/https:/https:ro
  backend:
    image: morishima/backend
    build:
      context: .
      dockerfile: BackEnd/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8081:80"
    volumes:
      - ~/.aspnet/https:/https:ro

